package JuegoMaya;
import Util.Jugador;
import Util.BD;
import Util.Botones;
import Util.LimiteCaracteres;
import Util.ReproductorSonido;

import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;
import javax.swing.JTextField;


public class Crucigrama extends javax.swing.JFrame {
    BD mBD;
    Jugador jugador;
    /**
     * Creates new form ola
     */
    ReproductorSonido reproductor = new ReproductorSonido();
    String palabra = "";
    int puntuacion = 0;
    boolean primeraR = false;
    boolean segundaR = false;
    boolean terceraR = false;
    boolean cuartaR = false;
    boolean quintaR = false;
    boolean sextaR = false;
    boolean septimaR = false;
    boolean octavaR = false;
    
    JTextField[] casillas;
    boolean[] estadoCasillas = new boolean[27];
    public Crucigrama(Jugador jugador) {
        this.jugador = jugador;
        mBD = new BD("BD_maya?useSSL=false","root","");
        initComponents();
        lblpuntuacionGlobal.setText(jugador.getPuntuacion()+"");
        if(!jugador.isOffline())
        {
            lblUsuario.setText(this.jugador.getUsuario());
        }
        Botones.transparenciaButton(btnImgRegresar);
        Botones.transparenciaButton(btnImgSoporte);
        Botones.transparenciaButton(btnImgInicio);
        casillas = new JTextField[]{txt1,txt2,txt3,txt4,txt5,txt6,txt7,txt8,txt9,
            txt10,txt11,txt12,txt13,txt14,txt15,txt16,txt17,txt18,txt19,txt20,
            txt21,txt22,txt23,txt24,txt25,txt26,txt27};
        for(int i = 0; i < 27; i++){
            estadoCasillas[i] = true;

            LimiteCaracteres.limitar(casillas[i], 1);
        }
        txt1.requestFocus();
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void puntuacion(int puntos){
        jugador.actualizarPuntuacion(puntos);
        if(!jugador.isOffline() && mBD.conectar()){
            mBD.actualizarPuntuacion(jugador);
        }
    }
    
    private void checarCaracter(JTextField jtf, java.awt.event.KeyEvent evt)
    {
        if(jtf.getText().length() >= 1)
        {
            evt.consume();
        }
    }
    private boolean comprobarPalabra(int numPalabra)
    {
        boolean palabraCorrecta = false;
        switch(numPalabra){
            case 1:
                palabra = txt1.getText()+txt2.getText()+txt3.getText()+txt4.getText();
                if("tres".equals(palabra) || "Tres".equals(palabra) || "TRES".equals(palabra))
                {
                    palabraCorrecta = true;
                    txt1.setEnabled(false);
                    estadoCasillas[0] = false;
                    txt2.setEnabled(false);
                    estadoCasillas[1] = false;
                    txt3.setEnabled(false);
                    estadoCasillas[2] = false;
                    txt4.setEnabled(false);
                    estadoCasillas[3] = false;
                    puntuacion(20);
                    puntuacion+=20;
                    lbPuntuacion.setText(Integer.toString(puntuacion));
                    primeraR = true;
                }
                break;
            case 2:
                palabra = txt9.getText()+txt6.getText()+txt10.getText()+txt11.getText();
                if("seis".equals(palabra) || "Seis".equals(palabra) || "SEIS".equals(palabra))
                {
                    palabraCorrecta = true;
                    txt9.setEnabled(false);
                    estadoCasillas[8] = false;
                    txt6.setEnabled(false);
                    estadoCasillas[5] = false;
                    txt10.setEnabled(false);
                    estadoCasillas[9] = false;
                    txt11.setEnabled(false);
                    estadoCasillas[10] = false;
                    puntuacion(20);
                    puntuacion+=20;
                    lbPuntuacion.setText(Integer.toString(puntuacion));
                    segundaR = true;
                }
                break;
            case 3:
                palabra = txt12.getText()+txt8.getText()+txt13.getText()+txt14.getText();
                if("cero".equals(palabra) || "Cero".equals(palabra) || "CERO".equals(palabra))
                {
                    palabraCorrecta = true;
                    txt12.setEnabled(false);
                    estadoCasillas[11] = false;
                    txt8.setEnabled(false);
                    estadoCasillas[7] = false;
                    txt13.setEnabled(false);
                    estadoCasillas[12] = false;
                    txt14.setEnabled(false);
                    estadoCasillas[13] = false;
                    puntuacion(20);
                    puntuacion+=20;
                    lbPuntuacion.setText(Integer.toString(puntuacion));
                    terceraR = true;
                }
                break;
            case 4:
                palabra = txt22.getText()+txt23.getText()+txt24.getText()+txt25.getText()+txt19.getText();
                if("cinco".equals(palabra) || "Cinco".equals(palabra) || "CINCO".equals(palabra))
                {
                    palabraCorrecta = true;
                    txt22.setEnabled(false);
                    estadoCasillas[21] = false;
                    txt23.setEnabled(false);
                    estadoCasillas[22] = false;
                    txt24.setEnabled(false);
                    estadoCasillas[23] = false;
                    txt19.setEnabled(false);
                    estadoCasillas[18] = false;
                    txt25.setEnabled(false);
                    estadoCasillas[24] = false;
                    puntuacion(20);
                    puntuacion+=20;
                    lbPuntuacion.setText(Integer.toString(puntuacion));
                    cuartaR = true;
                }
                break;
            case 5:
                palabra = txt4.getText()+txt5.getText()+txt6.getText()+txt7.getText()+txt8.getText();
                if("siete".equals(palabra) || "Siete".equals(palabra) || "SIETE".equals(palabra))
                {
                    palabraCorrecta = true;
                    txt4.setEnabled(false);
                    estadoCasillas[3] = false;
                    txt5.setEnabled(false);
                    estadoCasillas[4] = false;
                    txt6.setEnabled(false);
                    estadoCasillas[5] = false;
                    txt7.setEnabled(false); 
                    estadoCasillas[6] = false;
                    txt8.setEnabled(false);
                    estadoCasillas[7] = false;
                    puntuacion(20);
                    puntuacion+=20;
                    lbPuntuacion.setText(Integer.toString(puntuacion));
                    quintaR = true;
                }
                break;
            case 6:
                palabra = txt20.getText()+txt21.getText()+txt11.getText();
                if("dos".equals(palabra) || "Dos".equals(palabra) || "DOS".equals(palabra))
                {
                    palabraCorrecta = true;
                    txt20.setEnabled(false);
                    estadoCasillas[19] = false;
                    txt21.setEnabled(false);
                    estadoCasillas[20] = false;
                    txt11.setEnabled(false);
                    estadoCasillas[10] = false;
                    puntuacion(20);
                    puntuacion+=20;
                    lbPuntuacion.setText(Integer.toString(puntuacion));
                    sextaR = true;
                }
                break;
            case 7:
                palabra = txt12.getText()+txt15.getText()+txt16.getText()+txt17.getText()+txt18.getText()+txt19.getText();
                if("cuatro".equals(palabra) || "Cuatro".equals(palabra) || "CUATRO".equals(palabra))
                {
                    palabraCorrecta = true;
                    txt12.setEnabled(false);
                    estadoCasillas[11] = false;
                    txt15.setEnabled(false);
                    estadoCasillas[14] = false;
                    txt16.setEnabled(false);
                    estadoCasillas[15] = false;
                    txt17.setEnabled(false);
                    estadoCasillas[16] = false;
                    txt19.setEnabled(false);
                    estadoCasillas[18] = false;
                    txt18.setEnabled(false);
                    estadoCasillas[17] = false;
                    puntuacion(20);
                    puntuacion+=20;
                    lbPuntuacion.setText(Integer.toString(puntuacion));
                    septimaR = true;
                }
                break;
            case 8:
                palabra = txt26.getText()+txt24.getText()+txt27.getText();
                if("uno".equals(palabra) || "Uno".equals(palabra) || "UNO".equals(palabra))
                {
                    palabraCorrecta = true;
                    txt26.setEnabled(false);
                    estadoCasillas[25] = false;
                    txt24.setEnabled(false);
                    estadoCasillas[23] = false;
                    txt27.setEnabled(false);
                    estadoCasillas[26] = false;
                    puntuacion(20);
                    puntuacion+=20;
                    lbPuntuacion.setText(Integer.toString(puntuacion));
                    octavaR = true;
                }
                break;
        }
        if(primeraR && segundaR && terceraR && cuartaR && quintaR && sextaR && septimaR && octavaR)
        {
           JOptionPane.showMessageDialog(this, "Has ganado. Tu puntaje es: "+puntuacion, "Win!!", JOptionPane.INFORMATION_MESSAGE);
        }
        return palabraCorrecta;
    }
    
    private JTextField casillaCercana(int casillaActual) {
        JTextField casilla = null;
        for(int i = casillaActual+1; i < 27; i++){
            if(estadoCasillas[i]){
                casilla = casillas[i];
                break;
            }
        }
        if(casilla == null) {
            for(int i = 0; i < casillaActual; i++){
                if(estadoCasillas[i]){
                    casilla = casillas[i];
                    break;
                }
            }
        }
        return casilla;
    }
    
    private void checarCasilla(int casilla, int palabra, int keyCode){
        if((comprobarPalabra(palabra)) || 
                (keyCode == KeyEvent.VK_ENTER || keyCode == KeyEvent.VK_TAB && 
                casillas[casilla].getText().length() >= 1))
        {
            if(casillaCercana(casilla) != null) casillaCercana(casilla).requestFocus();
        }
    }
    
    private void checarCasilla(int casilla, int palabra1, int palabra2, int keyCode){
        if(comprobarPalabra(palabra1)){
            if(casillaCercana(casilla) != null) casillaCercana(casilla).requestFocus();
        }
        if((comprobarPalabra(palabra2)) || 
                (keyCode == KeyEvent.VK_ENTER || keyCode == KeyEvent.VK_TAB && 
                casillas[casilla].getText().length() >= 1))
        {
            if(casillaCercana(casilla) != null) casillaCercana(casilla).requestFocus();
        }
    }
    
    private void reproducirNumero(int i){
        //reproductor.cargarSonido(getClass().getResource("../sonidos/"+i+".wav"));
        reproductor.cargarSonido("/sonidos/"+i+".wav");
        reproductor.reproducir();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        txt1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txt2 = new javax.swing.JTextField();
        txt3 = new javax.swing.JTextField();
        txt4 = new javax.swing.JTextField();
        txt5 = new javax.swing.JTextField();
        txt6 = new javax.swing.JTextField();
        txt7 = new javax.swing.JTextField();
        txt8 = new javax.swing.JTextField();
        txt9 = new javax.swing.JTextField();
        txt10 = new javax.swing.JTextField();
        txt11 = new javax.swing.JTextField();
        txt13 = new javax.swing.JTextField();
        txt12 = new javax.swing.JTextField();
        txt14 = new javax.swing.JTextField();
        txt15 = new javax.swing.JTextField();
        txt16 = new javax.swing.JTextField();
        txt17 = new javax.swing.JTextField();
        txt18 = new javax.swing.JTextField();
        txt20 = new javax.swing.JTextField();
        txt21 = new javax.swing.JTextField();
        txt19 = new javax.swing.JTextField();
        txt26 = new javax.swing.JTextField();
        txt22 = new javax.swing.JTextField();
        txt27 = new javax.swing.JTextField();
        txt23 = new javax.swing.JTextField();
        txt24 = new javax.swing.JTextField();
        txt25 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        lbPuntuacion = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        btnImgSoporte = new javax.swing.JButton();
        btnImgRegresar = new javax.swing.JButton();
        btnImgInicio = new javax.swing.JButton();
        lblUsuario = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lblpuntuacionGlobal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("+Maya");

        jPanel3.setBackground(new java.awt.Color(255, 237, 213));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 648));

        txt1.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt1.setPreferredSize(new java.awt.Dimension(30, 30));
        txt1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt1KeyTyped(evt);
            }
        });

        jLabel2.setText("1");

        txt2.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt2.setPreferredSize(new java.awt.Dimension(30, 30));
        txt2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt2KeyTyped(evt);
            }
        });

        txt3.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt3.setPreferredSize(new java.awt.Dimension(30, 30));
        txt3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt3KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt3KeyTyped(evt);
            }
        });

        txt4.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt4.setPreferredSize(new java.awt.Dimension(30, 30));
        txt4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt4KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt4KeyTyped(evt);
            }
        });

        txt5.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt5.setPreferredSize(new java.awt.Dimension(30, 30));
        txt5.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt5KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt5KeyTyped(evt);
            }
        });

        txt6.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt6.setPreferredSize(new java.awt.Dimension(30, 30));
        txt6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt6KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt6KeyTyped(evt);
            }
        });

        txt7.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt7.setPreferredSize(new java.awt.Dimension(30, 30));
        txt7.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt7KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt7KeyTyped(evt);
            }
        });

        txt8.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt8.setPreferredSize(new java.awt.Dimension(30, 30));
        txt8.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt8KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt8KeyTyped(evt);
            }
        });

        txt9.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt9.setPreferredSize(new java.awt.Dimension(30, 30));
        txt9.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt9KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt9KeyTyped(evt);
            }
        });

        txt10.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt10.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt10.setPreferredSize(new java.awt.Dimension(30, 30));
        txt10.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt10KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt10KeyTyped(evt);
            }
        });

        txt11.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt11.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt11.setPreferredSize(new java.awt.Dimension(30, 30));
        txt11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt11KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt11KeyTyped(evt);
            }
        });

        txt13.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt13.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt13.setPreferredSize(new java.awt.Dimension(30, 30));
        txt13.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt13KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt13KeyTyped(evt);
            }
        });

        txt12.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt12.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt12.setPreferredSize(new java.awt.Dimension(30, 30));
        txt12.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt12KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt12KeyTyped(evt);
            }
        });

        txt14.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt14.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt14.setPreferredSize(new java.awt.Dimension(30, 30));
        txt14.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt14KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt14KeyTyped(evt);
            }
        });

        txt15.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt15.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt15.setPreferredSize(new java.awt.Dimension(30, 30));
        txt15.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt15KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt15KeyTyped(evt);
            }
        });

        txt16.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt16.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt16.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt16.setPreferredSize(new java.awt.Dimension(30, 30));
        txt16.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt16KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt16KeyTyped(evt);
            }
        });

        txt17.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt17.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt17.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt17.setPreferredSize(new java.awt.Dimension(30, 30));
        txt17.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt17KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt17KeyTyped(evt);
            }
        });

        txt18.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt18.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt18.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt18.setPreferredSize(new java.awt.Dimension(30, 30));
        txt18.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt18KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt18KeyTyped(evt);
            }
        });

        txt20.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt20.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt20.setPreferredSize(new java.awt.Dimension(30, 30));
        txt20.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt20KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt20KeyTyped(evt);
            }
        });

        txt21.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt21.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt21.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt21.setPreferredSize(new java.awt.Dimension(30, 30));
        txt21.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt21KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt21KeyTyped(evt);
            }
        });

        txt19.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt19.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt19.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt19.setPreferredSize(new java.awt.Dimension(30, 30));
        txt19.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt19KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt19KeyTyped(evt);
            }
        });

        txt26.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt26.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt26.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt26.setPreferredSize(new java.awt.Dimension(30, 30));
        txt26.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt26KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt26KeyTyped(evt);
            }
        });

        txt22.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt22.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt22.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt22.setPreferredSize(new java.awt.Dimension(30, 30));
        txt22.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt22KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt22KeyTyped(evt);
            }
        });

        txt27.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt27.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt27.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt27.setPreferredSize(new java.awt.Dimension(30, 30));
        txt27.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt27KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt27KeyTyped(evt);
            }
        });

        txt23.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt23.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt23.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt23.setPreferredSize(new java.awt.Dimension(30, 30));
        txt23.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt23KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt23KeyTyped(evt);
            }
        });

        txt24.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt24.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt24.setPreferredSize(new java.awt.Dimension(30, 30));
        txt24.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt24KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt24KeyTyped(evt);
            }
        });

        txt25.setFont(new java.awt.Font("Tahoma", 1, 30)); // NOI18N
        txt25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txt25.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        txt25.setPreferredSize(new java.awt.Dimension(30, 30));
        txt25.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txt25KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt25KeyTyped(evt);
            }
        });

        jLabel3.setText("2");

        jLabel4.setText("3");

        jLabel5.setText("4");

        jLabel6.setText("5");

        jLabel7.setText("6");

        jLabel8.setText("7");

        jLabel9.setText("8");

        jPanel2.setBackground(new java.awt.Color(247, 180, 114));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 168, 107), 4, true));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Horizontal");

        jLabel19.setBackground(new java.awt.Color(255, 255, 255));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCrucigrama/c6.png"))); // NOI18N
        jLabel19.setText(" 6.-");
        jLabel19.setToolTipText("");
        jLabel19.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel19.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel19.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel19MouseClicked(evt);
            }
        });

        jLabel17.setBackground(new java.awt.Color(255, 255, 255));
        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCrucigrama/c5.png"))); // NOI18N
        jLabel17.setText(" 5.-");
        jLabel17.setToolTipText("");
        jLabel17.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel17.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel17.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel17MouseClicked(evt);
            }
        });

        jLabel20.setBackground(new java.awt.Color(255, 255, 255));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCrucigrama/c8.png"))); // NOI18N
        jLabel20.setText(" 8.-");
        jLabel20.setToolTipText("");
        jLabel20.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel20.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel20.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel20MouseClicked(evt);
            }
        });

        jLabel18.setBackground(new java.awt.Color(255, 255, 255));
        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCrucigrama/c7.png"))); // NOI18N
        jLabel18.setText(" 7.-");
        jLabel18.setToolTipText("");
        jLabel18.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel18.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel18.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel18MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel19)
                    .addComponent(jLabel20))
                .addGap(19, 19, 19))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel11.setText("Puntuación:");

        lbPuntuacion.setText("0");

        jPanel1.setBackground(new java.awt.Color(247, 180, 114));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 168, 107), 4, true));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Vertical");
        jLabel1.setToolTipText("");

        jLabel13.setBackground(new java.awt.Color(255, 255, 255));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCrucigrama/c1.png"))); // NOI18N
        jLabel13.setText(" 1.-");
        jLabel13.setToolTipText("");
        jLabel13.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel13.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel13.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel13MouseClicked(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(255, 255, 255));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCrucigrama/c3.png"))); // NOI18N
        jLabel14.setText(" 3.-");
        jLabel14.setToolTipText("");
        jLabel14.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel14.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel14.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel14MouseClicked(evt);
            }
        });

        jLabel15.setBackground(new java.awt.Color(255, 255, 255));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCrucigrama/c2.png"))); // NOI18N
        jLabel15.setText(" 2.-");
        jLabel15.setToolTipText("");
        jLabel15.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel15.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel15MouseClicked(evt);
            }
        });

        jLabel16.setBackground(new java.awt.Color(255, 255, 255));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imgCrucigrama/c4.png"))); // NOI18N
        jLabel16.setText(" 4.-");
        jLabel16.setToolTipText("");
        jLabel16.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));
        jLabel16.setHorizontalTextPosition(javax.swing.SwingConstants.LEFT);
        jLabel16.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel16MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16))
                .addGap(19, 19, 19))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 12, Short.MAX_VALUE))
        );

        jLabel12.setFont(new java.awt.Font("Segoe UI Black", 1, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(162, 35, 29));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("CRUCIGRAMA");

        btnImgSoporte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngAyuda.png"))); // NOI18N
        btnImgSoporte.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImgSoporte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImgSoporte.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngAyuda1.png"))); // NOI18N
        btnImgSoporte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgSoporteActionPerformed(evt);
            }
        });

        btnImgRegresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngRegresar.png"))); // NOI18N
        btnImgRegresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImgRegresar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImgRegresar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngRegresar1.png"))); // NOI18N
        btnImgRegresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgRegresarActionPerformed(evt);
            }
        });

        btnImgInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngInicio.png"))); // NOI18N
        btnImgInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnImgInicio.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImgInicio.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pngInicio1.png"))); // NOI18N
        btnImgInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnImgInicioActionPerformed(evt);
            }
        });

        lblUsuario.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        lblUsuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Puntuación global:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(80, 80, 80)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(jLabel9)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(53, 53, 53)
                                                                .addComponent(jLabel3)
                                                                .addGap(69, 69, 69)
                                                                .addComponent(jLabel4)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                            .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                                        .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                    .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                                        .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                        .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                        .addGroup(jPanel3Layout.createSequentialGroup()
                                                                            .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                            .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                            .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel3Layout.createSequentialGroup()
                                                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addGroup(jPanel3Layout.createSequentialGroup()
                                                                                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(txt19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                                        .addGap(13, 13, 13)
                                                        .addComponent(jLabel2)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(txt23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(txt27, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(lbPuntuacion, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGap(357, 357, 357)
                                        .addComponent(jLabel5)
                                        .addGap(50, 50, 50)))
                                .addGap(75, 75, 75)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(177, 177, 177)
                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lblpuntuacionGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(18, 18, 18)
                                .addComponent(btnImgSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(40, 40, 40)
                            .addComponent(btnImgRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createSequentialGroup()
                            .addGap(825, 825, 825)
                            .addComponent(btnImgInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(btnImgSoporte, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnImgInicio, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 45, Short.MAX_VALUE)
                                        .addComponent(jLabel5)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(txt22, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txt23, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel2))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt27, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt26, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel9)
                                                    .addComponent(txt24, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt25, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(jLabel4)
                                                    .addComponent(jLabel3))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(txt3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt9, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt12, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt15, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt16, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt18, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt19, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(txt17, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txt4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt5, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt6, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt7, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt8, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txt10, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt13, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                    .addComponent(txt11, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt14, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt20, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(txt21, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                            .addGroup(jPanel3Layout.createSequentialGroup()
                                                .addComponent(jLabel6)
                                                .addGap(59, 59, 59)
                                                .addComponent(jLabel7)))
                                        .addGap(65, 65, 65)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel11)
                                            .addComponent(lbPuntuacion))
                                        .addGap(29, 29, 29))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(41, 41, 41)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel21)
                                            .addComponent(lblpuntuacionGlobal, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(26, 26, 26)
                                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(30, 30, 30)
                                .addComponent(btnImgRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(547, 547, 547)))
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txt1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyTyped
        checarCaracter(txt1,evt);
    }//GEN-LAST:event_txt1KeyTyped

    private void txt2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyTyped
         checarCaracter(txt2,evt);
    }//GEN-LAST:event_txt2KeyTyped

    private void txt3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt3KeyTyped
        checarCaracter(txt3,evt);
    }//GEN-LAST:event_txt3KeyTyped

    private void txt4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt4KeyTyped
        checarCaracter(txt4,evt);
    }//GEN-LAST:event_txt4KeyTyped

    private void txt5KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyTyped
        checarCaracter(txt5,evt);
    }//GEN-LAST:event_txt5KeyTyped

    private void txt6KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt6KeyTyped
        checarCaracter(txt6,evt);
    }//GEN-LAST:event_txt6KeyTyped

    private void txt7KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt7KeyTyped
        checarCaracter(txt7,evt);
    }//GEN-LAST:event_txt7KeyTyped

    private void txt8KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt8KeyTyped
        checarCaracter(txt8,evt);
    }//GEN-LAST:event_txt8KeyTyped

    private void txt9KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt9KeyTyped
        checarCaracter(txt9,evt);
    }//GEN-LAST:event_txt9KeyTyped

    private void txt10KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt10KeyTyped
        checarCaracter(txt10,evt);
    }//GEN-LAST:event_txt10KeyTyped

    private void txt11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt11KeyTyped
        checarCaracter(txt11,evt);
    }//GEN-LAST:event_txt11KeyTyped

    private void txt12KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt12KeyTyped
        checarCaracter(txt12,evt);
    }//GEN-LAST:event_txt12KeyTyped

    private void txt13KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt13KeyTyped
        checarCaracter(txt13,evt);
    }//GEN-LAST:event_txt13KeyTyped

    private void txt14KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt14KeyTyped
        checarCaracter(txt14,evt);
    }//GEN-LAST:event_txt14KeyTyped

    private void txt15KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt15KeyTyped
        checarCaracter(txt15,evt);
    }//GEN-LAST:event_txt15KeyTyped

    private void txt16KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt16KeyTyped
        checarCaracter(txt16,evt);
    }//GEN-LAST:event_txt16KeyTyped

    private void txt17KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt17KeyTyped
        checarCaracter(txt17,evt);
    }//GEN-LAST:event_txt17KeyTyped

    private void txt18KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt18KeyTyped
        checarCaracter(txt18,evt);
    }//GEN-LAST:event_txt18KeyTyped

    private void txt19KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt19KeyTyped
        checarCaracter(txt19,evt);
    }//GEN-LAST:event_txt19KeyTyped

    private void txt20KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt20KeyTyped
        checarCaracter(txt20,evt);
    }//GEN-LAST:event_txt20KeyTyped

    private void txt21KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt21KeyTyped
        checarCaracter(txt21,evt);
    }//GEN-LAST:event_txt21KeyTyped

    private void txt26KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt26KeyTyped
        checarCaracter(txt26,evt);
    }//GEN-LAST:event_txt26KeyTyped

    private void txt27KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt27KeyTyped
        checarCaracter(txt27,evt);
    }//GEN-LAST:event_txt27KeyTyped

    private void txt22KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt22KeyTyped
        checarCaracter(txt22,evt);
    }//GEN-LAST:event_txt22KeyTyped

    private void txt23KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt23KeyTyped
        checarCaracter(txt23,evt);
    }//GEN-LAST:event_txt23KeyTyped

    private void txt24KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt24KeyTyped
        checarCaracter(txt24,evt);
    }//GEN-LAST:event_txt24KeyTyped

    private void txt25KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt25KeyTyped
        checarCaracter(txt25,evt);
    }//GEN-LAST:event_txt25KeyTyped

    private void txt1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt1KeyReleased
        checarCasilla(0, 1, evt.getKeyCode());
    }//GEN-LAST:event_txt1KeyReleased

    private void txt2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt2KeyReleased
        checarCasilla(1, 1, evt.getKeyCode());
    }//GEN-LAST:event_txt2KeyReleased

    private void txt3KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt3KeyReleased
        checarCasilla(2, 1, evt.getKeyCode());
    }//GEN-LAST:event_txt3KeyReleased

    private void txt4KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt4KeyReleased
        checarCasilla(3, 1, 5, evt.getKeyCode());
    }//GEN-LAST:event_txt4KeyReleased

    private void txt5KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt5KeyReleased
        checarCasilla(4, 5, evt.getKeyCode());
    }//GEN-LAST:event_txt5KeyReleased

    private void txt6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt6KeyReleased
        checarCasilla(5, 5, 2, evt.getKeyCode());
    }//GEN-LAST:event_txt6KeyReleased

    private void txt7KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt7KeyReleased
        checarCasilla(6, 5, evt.getKeyCode());
    }//GEN-LAST:event_txt7KeyReleased

    private void txt8KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt8KeyReleased
        checarCasilla(7, 5, 3, evt.getKeyCode());
    }//GEN-LAST:event_txt8KeyReleased

    private void txt9KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt9KeyReleased
        checarCasilla(8, 2, evt.getKeyCode());
    }//GEN-LAST:event_txt9KeyReleased

    private void txt10KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt10KeyReleased
        checarCasilla(9, 2, evt.getKeyCode());
    }//GEN-LAST:event_txt10KeyReleased

    private void txt11KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt11KeyReleased
        checarCasilla(10, 2, 6, evt.getKeyCode());
    }//GEN-LAST:event_txt11KeyReleased

    private void txt12KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt12KeyReleased
        checarCasilla(11, 3, 7, evt.getKeyCode());
    }//GEN-LAST:event_txt12KeyReleased

    private void txt13KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt13KeyReleased
        checarCasilla(12, 3, evt.getKeyCode());
    }//GEN-LAST:event_txt13KeyReleased

    private void txt14KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt14KeyReleased
        checarCasilla(13, 3, evt.getKeyCode());
    }//GEN-LAST:event_txt14KeyReleased

    private void txt22KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt22KeyReleased
        checarCasilla(21, 4, evt.getKeyCode());
    }//GEN-LAST:event_txt22KeyReleased

    private void txt23KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt23KeyReleased
        checarCasilla(22, 4, evt.getKeyCode());
    }//GEN-LAST:event_txt23KeyReleased

    private void txt24KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt24KeyReleased
        checarCasilla(23, 4, 8, evt.getKeyCode());
    }//GEN-LAST:event_txt24KeyReleased

    private void txt25KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt25KeyReleased
        checarCasilla(24, 4, evt.getKeyCode());
    }//GEN-LAST:event_txt25KeyReleased

    private void txt19KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt19KeyReleased
       checarCasilla(18, 7, 4, evt.getKeyCode());
    }//GEN-LAST:event_txt19KeyReleased

    private void txt20KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt20KeyReleased
        checarCasilla(19, 6, evt.getKeyCode());
    }//GEN-LAST:event_txt20KeyReleased

    private void txt21KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt21KeyReleased
        checarCasilla(20, 6, evt.getKeyCode());
    }//GEN-LAST:event_txt21KeyReleased

    private void txt15KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt15KeyReleased
        checarCasilla(14, 7, evt.getKeyCode());
    }//GEN-LAST:event_txt15KeyReleased

    private void txt16KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt16KeyReleased
        checarCasilla(15, 7, evt.getKeyCode());
    }//GEN-LAST:event_txt16KeyReleased

    private void txt17KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt17KeyReleased
        checarCasilla(16, 7, evt.getKeyCode());
    }//GEN-LAST:event_txt17KeyReleased

    private void txt18KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt18KeyReleased
        checarCasilla(17, 7, evt.getKeyCode());
    }//GEN-LAST:event_txt18KeyReleased

    private void txt26KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt26KeyReleased
        checarCasilla(25, 8, evt.getKeyCode());
    }//GEN-LAST:event_txt26KeyReleased

    private void txt27KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt27KeyReleased
        checarCasilla(26, 8, evt.getKeyCode());
    }//GEN-LAST:event_txt27KeyReleased

    private void btnImgRegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgRegresarActionPerformed
        JuegosNumeros regresar = new JuegosNumeros(jugador);
        regresar.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnImgRegresarActionPerformed

    private void btnImgSoporteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgSoporteActionPerformed
        JOptionPane.showMessageDialog(this, "Escribe el numero que corresponde en los recuadros\nNota: Si presionas en las pistas, puedes escuchar"
                + "\nla pronunciación de los números", "Instrucciones", JOptionPane.INFORMATION_MESSAGE);        
    }//GEN-LAST:event_btnImgSoporteActionPerformed

    private void btnImgInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnImgInicioActionPerformed
        MenuPrincipal inicio = new MenuPrincipal();
        inicio.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnImgInicioActionPerformed

    private void jLabel13MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel13MouseClicked
        reproducirNumero(3);
    }//GEN-LAST:event_jLabel13MouseClicked

    private void jLabel15MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel15MouseClicked
        reproducirNumero(6);
    }//GEN-LAST:event_jLabel15MouseClicked

    private void jLabel14MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel14MouseClicked
        reproducirNumero(0);
    }//GEN-LAST:event_jLabel14MouseClicked

    private void jLabel16MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel16MouseClicked
        reproducirNumero(5);
    }//GEN-LAST:event_jLabel16MouseClicked

    private void jLabel17MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel17MouseClicked
        reproducirNumero(7);
    }//GEN-LAST:event_jLabel17MouseClicked

    private void jLabel19MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel19MouseClicked
        reproducirNumero(2);
    }//GEN-LAST:event_jLabel19MouseClicked

    private void jLabel18MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel18MouseClicked
        reproducirNumero(4);
    }//GEN-LAST:event_jLabel18MouseClicked

    private void jLabel20MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel20MouseClicked
        reproducirNumero(1);
    }//GEN-LAST:event_jLabel20MouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(Crucigrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(Crucigrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(Crucigrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(Crucigrama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                Jugador jugador = new Jugador("","");
//                jugador.offline();
//                new Crucigrama(jugador).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnImgInicio;
    private javax.swing.JButton btnImgRegresar;
    private javax.swing.JButton btnImgSoporte;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbPuntuacion;
    private javax.swing.JLabel lblUsuario;
    private javax.swing.JLabel lblpuntuacionGlobal;
    private javax.swing.JTextField txt1;
    private javax.swing.JTextField txt10;
    private javax.swing.JTextField txt11;
    private javax.swing.JTextField txt12;
    private javax.swing.JTextField txt13;
    private javax.swing.JTextField txt14;
    private javax.swing.JTextField txt15;
    private javax.swing.JTextField txt16;
    private javax.swing.JTextField txt17;
    private javax.swing.JTextField txt18;
    private javax.swing.JTextField txt19;
    private javax.swing.JTextField txt2;
    private javax.swing.JTextField txt20;
    private javax.swing.JTextField txt21;
    private javax.swing.JTextField txt22;
    private javax.swing.JTextField txt23;
    private javax.swing.JTextField txt24;
    private javax.swing.JTextField txt25;
    private javax.swing.JTextField txt26;
    private javax.swing.JTextField txt27;
    private javax.swing.JTextField txt3;
    private javax.swing.JTextField txt4;
    private javax.swing.JTextField txt5;
    private javax.swing.JTextField txt6;
    private javax.swing.JTextField txt7;
    private javax.swing.JTextField txt8;
    private javax.swing.JTextField txt9;
    // End of variables declaration//GEN-END:variables

    private String toString(int puntuacion) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
